# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('gender_match', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('a', 'Bread'), ('a', 'All')], default='m', help_text="Gender for the user's match.", max_length=2)),
                ('first_name', models.CharField(default='', help_text="The user's first name.", max_length=128)),
                ('last_name', models.CharField(default='', help_text="The user's last name.", max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('liked', models.ManyToManyField(blank=True, related_name='_user_liked_+', to=settings.AUTH_USER_MODEL)),
                ('matches', models.ManyToManyField(blank=True, related_name='_user_matches_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MemeConnect Users',
                'db_table': 'users',
                'verbose_name': 'MemeConnect User',
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'memes',
            },
        ),
        migrations.CreateModel(
            name='MemeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=256)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rater.Meme')),
                ('users_who_liked', models.ManyToManyField(related_name='liked_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meme_images',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='meme',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='memes', to='rater.Tag'),
        ),
    ]
