# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memeimage',
            name='users_who_liked',
        ),
        migrations.AddField(
            model_name='user',
            name='memes',
            field=models.ManyToManyField(related_name='users_who_liked', to='rater.MemeImage'),
        ),
    ]
