# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memeway


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0002_auto_20170114_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=memeway.random_generator, max_length=16)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_me_ignore_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatrooms',
            },
        ),
    ]
