# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0002_auto_20170114_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'meme_images',
            },
        ),
        migrations.RemoveField(
            model_name='meme',
            name='safe_url',
        ),
        migrations.AddField(
            model_name='memeimage',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rater.Meme'),
        ),
    ]
