# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0003_auto_20170114_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosenmeme',
            name='meme',
        ),
        migrations.RemoveField(
            model_name='chosenmeme',
            name='user',
        ),
        migrations.AddField(
            model_name='memeimage',
            name='user_who_liked',
            field=models.ManyToManyField(related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChosenMeme',
        ),
    ]
