# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0006_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender_match',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('a', 'Bread'), ('o', 'Other')], default='m', help_text="Gender for the user's match.", max_length=2),
        ),
    ]
