# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0009_auto_20170115_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
    ]
