# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0010_user_downvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_viewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
