# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0011_user_last_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
