# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0012_auto_20170115_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user_2',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
