# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0013_auto_20170115_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default="My life is a meme 'cuz I have no description!"),
        ),
    ]
