# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0014_auto_20170115_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeimage',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memeimage',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
