# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rater', '0015_auto_20170115_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=128),
        ),
    ]
